global:
  namespace: "" # add namespace here
  useTTY: true

# Override value example for full-node from main chart
moniker: '' # add node moniker here

secretProvider:
  enabled: false

cometbft:
  config:
    p2p:
      externalAddress: "" # Add external address
  secrets: # TODO: Add secrets, recommended not to use devContent in prodcution environments
      nodeKey:
        filename: nodeKey.json
        devContent:
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"
      privValidatorKey:
        filename: privValidatorKey.json
        devContent:
          # Ed25519 address of validator
          address: ""  # can override with a value for local testing
          # public key for the validator address
          pub_key:
            type: tendermint/PubKeyEd25519
            value: ""  # can override with a value for local testing
          # private key for the validator address
          # This is a secret key, should use a secret manager for production deployments
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"

genesis:
  chainId: astria-dusk-11
  genesisTime: "2024-07-27T00:49:11.964127Z"
  authoritySudoAddress: astria1hwxgjjp8f7a46a2sr0mxffn5r7udkpfrcavpul
  allowedFeeAssets: []
  ibc:
    enabled: true
    inboundEnabled: true
    outboundEnabled: true
    sudoAddress: astria10z89e25n2fs754a0v9nnsh0kvzh90wf4ukk6jc
    relayerAddresses: []
  genesisAccounts:
    - address: astria1hwxgjjp8f7a46a2sr0mxffn5r7udkpfrcavpul
      balance: "333333333333333333"
    - address: astria1luwmgezc63qg0jt4aw5ey207tw7dcd20fqt44z
      balance: "333333333333333333"
    - address: astria1g9p32uu5r4am2uae0n0xfnxpnqmlymrh9yrqng
      balance: "333333333333333333"
    - address: astria1ved3v3k2a80wad756xhwd7r75ycuaf6z9y60rl
      balance: "333333333333333333"
    - address: astria1yqdjnnmrp7w5ygwj0dkldsgzjhv5vcakp7yeu9
      balance: "60"
    - address: astria1f0dw5muma062mwfz7g46229adaycpjevnyw9fc
      balance: "1000000000000"
  validators:
    - name: node0
      power: '1'
      address: FDDBAF2EFB176DD25A3EDDE9106E78D329A38562
      pubKey: U46eweNkf5swUyu45cK0qABsaxFoPL7OK+Hqqahr8fg=
    - name: node1
      address: 2F5AEE50975F56F59C4C5248277CB1E4A8320593
      pubKey: pJeqSiLKgjKHYIKSCxEGeJiMhhlLDC4SoE3Pb1Noi7I=
      power: '1'
    - name: node2
      power: '1'
      address: C8FAD5B264F7D5B5446978E96AEC3549E41F1353
      pubKey: /zck8pXQM9AzdBaDsfaoTkRxQgQQyGoCC3q1Ohirlbc=
    - name: node3
      power: '1'
      address: 0DC9BAF2CB94F4897F2A569EF2A33EE1D4E7B50B
      pubKey: E6gYdFSWp8SQYd60JSZBhADZgB8lV8FAbqsmAvX6RPY=
        
sequencer:
  metrics:
    enabled: true
  otel:
    enabled: true
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesCompression: gzip
    tracesTimeout: 10
    otlpHeaders: ""
    traceHeaders: ""

cometbft:
  config:
    logLevel: "debug"
    p2p:
      laddr: "tcp://0.0.0.0"
      seeds: []
      # List of nodes to keep persistent connections to
      persistentPeers:
        - f4b8a8dcfc5a142bd00aadab71f39dbfe7091d13@35.236.5.36:26656
        - ca3bc3562919b82575fe3ac5b11fa5962ce8cd3b@34.94.1.224:26656
        - 4418000e355967ecc8e03004f5850dfde51c410b@34.102.98.161:26656
        - 7a117e7906d8428ad20341aca94af03c980c11d8@34.102.109.86:26656

storage:
  enabled: true
  local: false

serviceMonitor:
  enabled: true

ingress:
  p2p:
    enabled: false

resources:
  cometbft:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  sequencer:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
