global:
  namespace: astria-dusk9-cluster
  useTTY: true

images:
  sequencer:
    tag: "0.15.0"

# Override value example for full-node from main chart
moniker: 'fullnode'

cometbft:
  config:
    p2p:
      externalAddress: "" #TODO: Add external address
  secrets: # TODO: Add secrets, recommended not to use devContent in prodcution environments
      nodeKey:
        filename: nodeKey.json
        devContent:
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"
      privValidatorKey:
        filename: privValidatorKey.json
        devContent:
          # Ed25519 address of validator
          address: ""  # can override with a value for local testing
          # public key for the validator address
          pub_key:
            type: tendermint/PubKeyEd25519
            value: ""  # can override with a value for local testing
          # private key for the validator address
          # This is a secret key, should use a secret manager for production deployments
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"

genesis:
  chainId: astria-dusk-9
  genesisTime: "2024-07-27T00:49:11.964127Z"
  authoritySudoAddress: astria1d8kas2u23k588ygyf7xue34y28vr474qmmt32h
  allowedFeeAssets: []
  ibc:
    enabled: true
    inboundEnabled: true
    outboundEnabled: true
    sudoAddress: astria1w5fnh0cjxa5thvzk4hcwvvx8te2l6c24xknpvv
    relayerAddresses: [] # relayer address - astria1uz8jpx4fq6ne63lzjulcxzthzsjrqfedl9yhdg
  genesisAccounts:
    # Wallet address used for composer on EVM
    - address: astria1uhk0zehfej785erhrd6822r0f2d273vyxpnc6w
      balance: "33333333333333333333333333"
    # dusk-9-funded-pkey
    - address: astria1syfaefrfj66mpuldl3rx8twjqwcaf3cc84g36h
      balance: "3402823669209384634633746074317682"
    # Used for sequencer faucet
    - address: astria12t5ahmm4ldhhse30klvq0nyf4zccdfa0kx5j6u
      balance: "33333333333333333333333333"
    # Account to be utilized as bridge account for EVM
    - address: astria1q9kwhu2d6hga4p9qhvwg3vgd7f4jfx8gl9mzwc
      balance: "60"
  validators:
    - name: node0
      power: '6'
      address: FDDBAF2EFB176DD25A3EDDE9106E78D329A38562
      pubKey: U46eweNkf5swUyu45cK0qABsaxFoPL7OK+Hqqahr8fg=
    - name: node1
      address: 2F5AEE50975F56F59C4C5248277CB1E4A8320593
      pubKey: pJeqSiLKgjKHYIKSCxEGeJiMhhlLDC4SoE3Pb1Noi7I=
      power: '6'
    - name: node2
      power: '6'
      address: C8FAD5B264F7D5B5446978E96AEC3549E41F1353
      pubKey: /zck8pXQM9AzdBaDsfaoTkRxQgQQyGoCC3q1Ohirlbc=
    - name: node3
      power: '9'
      address: 0DC9BAF2CB94F4897F2A569EF2A33EE1D4E7B50B
      pubKey: E6gYdFSWp8SQYd60JSZBhADZgB8lV8FAbqsmAvX6RPY=
        
sequencer:
  metrics:
    enabled: true
  otel:
    enabled: true
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesCompression: gzip
    tracesTimeout: 10
    otlpHeaders: ""
    traceHeaders: ""

cometbft:
  config:
    logLevel: "debug"
    p2p:
      laddr: "tcp://0.0.0.0"
      seeds: []
      # List of nodes to keep persistent connections to
      persistentPeers:
        - f4b8a8dcfc5a142bd00aadab71f39dbfe7091d13@35.236.34.165:26656
        - ca3bc3562919b82575fe3ac5b11fa5962ce8cd3b@34.94.77.164:26656
        - 4418000e355967ecc8e03004f5850dfde51c410b@34.94.1.39:26656
        - 7a117e7906d8428ad20341aca94af03c980c11d8@34.94.8.154:26656

secretProvider:
  enabled: true

storage:
  enabled: true
  local: false
  entities:
    sequencerSharedStorage:
      size: 1Ti
      storageClassName: premium-rwo
      persistentVolumeName: "sequencer-shared-storage"
      path: "/data/sequencer-data"

serviceMonitor:
  enabled: true

ingress:
  p2p:
    enabled: false

resources:
  cometbft:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  sequencer:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
