global:
  useTTY: true

images:
  sequencer:
    tag: "0.13.0"

config:
  sequencer:
    authoritySudoAddress: c97a5efdc2744b6818b49245a5952d4d644592c1
    ibc:
      enabled: true
      inboundEnabled: true
      outboundEnabled: true
      sudoAddress: 59dd5630cf6cb06c79e56c2070d46e4c14325c3b
      relayerAddresses: []

    genesisAccounts:
      - address: 7ffff0900203ef6325645429a1fd0fbc9b431639
        balance: "333333333333333333"
      - address: d286ad9debd49cb569f8a9dc790ae9eed61b76a4
        balance: "340282366920938463463374607431768211455"
      - address: 35527f8eea7aa7e29de390897e2ba5595d5beb10
        balance: "333333333333333333"
      - address: 18cee9ad8d8f4586b01c7efd9fd83e291e90e35d
        balance: "333333333333333333"
      - address: 3cabc640b991615e26d1ff93ea872ea1fa1b2027
        balance: "60"

    otel:
      enabled: true
      endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
      tracesEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
      tracesCompression: gzip
      tracesTimeout: 10
      otlpHeaders: ""
      traceHeaders: ""

  # Values for CometBFT node configuration
  cometBFT:
    chainId: astria-dusk-7
    genesisTime: "2024-05-20T00:49:11.964127Z"
    validators:
      - name: node0
        power: '1'
        address: FDDBAF2EFB176DD25A3EDDE9106E78D329A38562
        pubKey: U46eweNkf5swUyu45cK0qABsaxFoPL7OK+Hqqahr8fg=
      - name: node1
        address: 2F5AEE50975F56F59C4C5248277CB1E4A8320593
        pubKey: pJeqSiLKgjKHYIKSCxEGeJiMhhlLDC4SoE3Pb1Noi7I=
        power: '1'
      - name: node2
        power: '1'
        address: C8FAD5B264F7D5B5446978E96AEC3549E41F1353
        pubKey: /zck8pXQM9AzdBaDsfaoTkRxQgQQyGoCC3q1Ohirlbc=
      - name: node3
        power: '1'
        address: 0DC9BAF2CB94F4897F2A569EF2A33EE1D4E7B50B
        pubKey: E6gYdFSWp8SQYd60JSZBhADZgB8lV8FAbqsmAvX6RPY=


storage:
  enabled: true
  local: false
  entities:
    sequencerSharedStorage:
      size: 1Ti
      storageClassName: premium-rwo
      persistentVolumeName: "sequencer-shared-storage"
      path: "/data/sequencer-data"

serviceMonitor:
  enabled: false

ingress:
  rpc: 
    enabled: false
  grpc:
    enabled: false
  p2p:
    enabled: false

sequencer-relayer:
  enabled: false
