global:
  namespace: "" # add namespace here
  useTTY: true

# Override value example for full-node from main chart
moniker: '' # add moniker here

images:
  sequencer:
    tag: "1.0.0"
  cometbft:
    tag: "v0.38.11"

# When deploying in a production environment should use a secret provider
# This is configured for use with GCP, need to set own resource names
# and keys
#
# Secret provider utilizes Secret Store CSI Driver
# See docs: https://secrets-store-csi-driver.sigs.k8s.io/introduction
secretProvider:
  enabled: false
  provider: gcp
  # May need to update this template to match the secret provider
  # it will be passed an object of the form:
  # { <secret_name>: {
  #     filename: <filename>,
  #     secret: { resourceName: <resourceName> }
  #   }
  # }
  #
  # Can update the source of the secrets at config.cometBFT.secrets to
  # match the secret provider's requirements. The default works for GCP.
  # The secret file must be mapped to the <secret_name>.filename value.
  parametersTemplate: |-
    secrets: |
      {{- range $value := .Values.cometbft.secrets }}
      - resourceName: {{ $value.secret.resourceName }}
        fileName: "{{ $value.filename }}"
      {{- end }}

cometbft:
  config:
    p2p:
      # List of nodes to keep persistent connections to
      persistentPeers:
        - 472667f76caa59499d023836f34305fb1b879202@34.146.155.71:26656
        - 7c63e5951433cd144dcd28ff822b696294e747ce@35.243.92.67:26656
        - 845cd82094c83188af13f3a6a33cf825a2764ba2@34.84.168.120:26656
        - 2c5f26275c1b2f09712792d19247f83095b2e21a@34.84.217.48:26656

  # When secret Provider is enabled the secret will be loaded through the resource
  # name. The devcontent solution is intended only for insecure testing setups.
  secrets: 
    nodeKey:
      filename: nodeKey.json
      devContent:
        priv_key:
          type: tendermint/PrivKeyEd25519
          value: ""  # can override with a value for local testing
      secret:
        resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"
    privValidatorKey:
      filename: privValidatorKey.json
      devContent:
        # Ed25519 address of validator
        address: ""  # can override with a value for local testing
        # public key for the validator address
        pub_key:
          type: tendermint/PubKeyEd25519
          value: ""  # can override with a value for local testing
        # private key for the validator address
        # This is a secret key, should use a secret manager for production deployments
        priv_key:
          type: tendermint/PrivKeyEd25519
          value: ""  # can override with a value for local testing
      secret:
        resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"

genesis:
  chainId: astria
  genesisTime: "2024-10-25T21:20:00.000000Z"
  authoritySudoAddress: astria1f7d96l29kz22q2tcwrpg925dxt7z8jtsjgs9uh
  nativeAssetBaseDenomination: false
  allowedFeeAssets: []
  ibc:
    enabled: true
    inboundEnabled: true
    outboundEnabled: true
    sudoAddress: astria1v70qrgnua42f4x3kl40d60ae2zftftmqe4c7gy
    relayerAddresses:
      - astria1pz0txxwcenc98vx6alnprcef46kyrvrya8cs8p
  genesisAccounts: []
  fees:
    feeChange:
      base: "0"
      multiplier: "0"
    sudoAddressChange:
      base: "0"
      multiplier: "0"
    feeAssetChange:
      base: "0"
      multiplier: "0"
    validatorUpdate:
      base: "0"
      multiplier: "0"
    ibcSudoChange:
      base: "0"
      multiplier: "0"
    ibcRelayerChange:
      base: "0"
      multiplier: "0"
    ibcRelay:
      base: "0"
      multiplier: "0"
    initBridgeAccount:
      base: "10000000"
      multiplier: "0"
    bridgeSudoChange:
      base: "1000000"
      multiplier: "0"
    rollupDataSubmission: false
    bridgeLock: false
    transfer: false
    bridgeUnlock: false
    ics20Withdrawal: false
  validators:
    # Astria astria0
    - name: astria0
      power: '100'
      address: 63FD0CE49F485F167A8B94B9E80DBBD351FA9F98
      pubKey: 8rPKInUBqFKv7Wie/O4G9P6wHWccMfifpeU/BlhFaHw=
    # Astria astria1
    - name: astria1
      power: '100'
      address: 4E72A7432B5C0FAEC21CF251535781723A8248A7
      pubKey: IzGYindOUk15ZL6bh6j8+fjSRgjeoL93txgA9ETfFXI=
    # Astria astria2
    - name: astria2
      power: '100'
      address: 47BD55BC6E3CA4A8519C372744AEE40C9340B8B4
      pubKey: S9VKKZgwdtiWWll3PT1yn+xgqZLci+MMtPmH2wuux+w=
    # Astria node3
    - name: astria3
      power: '100'
      address: 3A7E64DFA6E11958B5A0903EA4C3D5A8E662C503
      pubKey: XntgAVoWJS7SE7hSw9OHyHBrP50+l8mZc/ctaQWIseQ=
    # Nodes.Guru
    - name: Nodes.Guru
      power: '25'
      address: 8F6D2388C4C068A0217F75E914C3FBA8E28079B7
      pubKey: S4vhA0z7Gw5p3Yszwnlm+BdXELSOeRH4/jBL2r55zo8=
    # Qubelabs
    - name: Qubelabs
      power: '25'
      address: 3CB3760D29B485C711D27D5AC5CE6B4AF048263D
      pubKey: KA/DKcILRpYVybz9ZHh784yZr9WvvCHRKzy+Av9KlUg=
    # DSRV
    - name: DSRV
      power: '25'
      address: 19685F5CFF69B64EF6C50E8BB4BA506DB1E1BB5C
      pubKey: jqnJZ1Op4TPiNTHNVFyvXtdRuObhDhnl1cKyH/FO3kY=
    # Nocturnal Labs
    - name: Nocturnal Labs
      power: '25'
      address: 816B7C75D3C43D5F700D67975F020D938AF882F9
      pubKey: IdsrfKarwcDa0ToNrDfRXPByuYdlwSDxvwJlJM0mc9A=
    # P-OPS Team
    - name: P-OPS Team
      power: '25'
      address: 4E8AD81B9361FBF6DBC853514F1B259A75B2D5C0
      pubKey: hCbuIHcC8Ivufr1hR/cPUPetS0snT9fSzgMQgWKZx9c=
    # Tessellated
    - name: Tessellated
      power: '25'
      address: 666CBCE466D0DECDBBB3982AF747B74E0BD44030
      pubKey: gyhVdvDyxSV2XH0jby1vnmQitPowjm/pn1CDVprre2c=
    # P2P.ORG - P2P Validator
    - name: P2P.ORG - P2P Validator
      power: '25'
      address: 4FBB2E3BF3B5DDD7FCD5C4A028336F680098A1FB
      pubKey: GLN47O9Iea9yKR9m8FMpZ180KL52Ht1i3yO9xu760Ew=

sequencer:
  metrics:
    enabled: true
  otel:
    enabled: true
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesCompression: gzip
    tracesTimeout: 10
    otlpHeaders: ""
    traceHeaders: ""

# update storage for your storage provider
storage:
  enabled: true
  local: false
  entities:
    sequencerSharedStorage:
      size: 1Ti
      storageClassName: premium-rwo
      persistentVolumeName: "sequencer-shared-storage"
      path: "/data/sequencer-data"

serviceMonitor:
  enabled: false

resources:
  cometbft:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  sequencer:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi

# See the default chart value file for information on configuring ingress
ingress:
  p2p:
    enabled: false
  rpc:
    enabled: false
  grpc:
    enabled: false
