global:
  namespace: "" # add namespace here
  useTTY: true

# Override value example for full-node from main chart
moniker: 'fullnode'

secretProvider:
  enabled: false

cometbft:
  config:
    p2p:
      externalAddress: "" #TODO: Add external address
  secrets: # TODO: Add secrets, recommended not to use devContent in prodcution environments
      nodeKey:
        filename: nodeKey.json
        devContent:
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"
      privValidatorKey:
        filename: privValidatorKey.json
        devContent:
          # Ed25519 address of validator
          address: ""  # can override with a value for local testing
          # public key for the validator address
          pub_key:
            type: tendermint/PubKeyEd25519
            value: ""  # can override with a value for local testing
          # private key for the validator address
          # This is a secret key, should use a secret manager for production deployments
          priv_key:
            type: tendermint/PrivKeyEd25519
            value: ""  # can override with a value for local testing
        secret:
          resourceName: "projects/$PROJECT_ID/secrets/privValidatorKey/versions/latest"

genesis:
  chainId: astria-dusk-10
  genesisTime: "2024-07-27T00:49:11.964127Z"
  # dusk-10-sudo-key-pkey
  authoritySudoAddress: astria12znlg972crgwspaw2ljsnglsvs0yk2waf7wxqw
  allowedFeeAssets: [] # TODO: will be enabled via sudo command.
  ibc:
    enabled: true
    inboundEnabled: true
    outboundEnabled: true
    # dusk-10-ibc-sudo-pkey
    sudoAddress: astria1x62tjjddjspjquk503ww6l2nck46vxjaz6nq4f
    relayerAddresses: [] # TODO: will be enabled via sudo command. use  as relayer address
  genesisAccounts:
    # Wallet address used as sudo address
    - address: astria12znlg972crgwspaw2ljsnglsvs0yk2waf7wxqw
      balance: "333333333333333333"
    # Wallet address used for composer on EVM
    # GCP secret "dusk-10-evm-composer-pkey"
    - address: astria14arwxsq84vjj0eeywah8e80lt6ehgunkn7pxf7
      balance: "333333333333333333"
    # GCP Secret "dusk-10-funded-pkey"
    - address: astria1umqxfss8wua2ptcclwf7z3ly9phvsjt0hxpcjm
      balance: "333333333333333333"
    # Used for sequencer faucet
    # GCP Secret "dusk-10-seq-faucet-pkey"
    - address: astria1hrukdtz6xxk4x0hjrvc2wlx9wqc86s6u6tjmhy
      balance: "333333333333333333"
    # Account to be utilized as bridge account for EVM
    # GCP Secret "dusk-10-evm-native-bridge-pkey"
    - address: astria1je48an7fhxfl70nv5x4s4mphe7nszm6t0fryy7
      balance: "60"
    # Account to be utilized as relayer account for mocha-4 ibc
    # GCP Secret "dusk-10-sequencer-ibc-relayer-pkey"
    - address: astria10cgc54dxh3sdetsr03rkhhkt3vsn3r7j46yvqh
      balance: "1000000000000"
  validators:
    - name: node0
      power: '1'
      address: FDDBAF2EFB176DD25A3EDDE9106E78D329A38562
      pubKey: U46eweNkf5swUyu45cK0qABsaxFoPL7OK+Hqqahr8fg=
    - name: node1
      address: 2F5AEE50975F56F59C4C5248277CB1E4A8320593
      pubKey: pJeqSiLKgjKHYIKSCxEGeJiMhhlLDC4SoE3Pb1Noi7I=
      power: '1'
    - name: node2
      power: '1'
      address: C8FAD5B264F7D5B5446978E96AEC3549E41F1353
      pubKey: /zck8pXQM9AzdBaDsfaoTkRxQgQQyGoCC3q1Ohirlbc=
    - name: node3
      power: '1'
      address: 0DC9BAF2CB94F4897F2A569EF2A33EE1D4E7B50B
      pubKey: E6gYdFSWp8SQYd60JSZBhADZgB8lV8FAbqsmAvX6RPY=
        
sequencer:
  metrics:
    enabled: true
  otel:
    enabled: true
    endpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesEndpoint: http://otel-collector.monitoring.svc.cluster.local:4317
    tracesCompression: gzip
    tracesTimeout: 10
    otlpHeaders: ""
    traceHeaders: ""

cometbft:
  config:
    logLevel: "debug"
    p2p:
      laddr: "tcp://0.0.0.0"
      seeds: []
      # List of nodes to keep persistent connections to
      persistentPeers:
        - f4b8a8dcfc5a142bd00aadab71f39dbfe7091d13@35.236.107.39:26656
        - ca3bc3562919b82575fe3ac5b11fa5962ce8cd3b@34.118.249.169:26656
        - 4418000e355967ecc8e03004f5850dfde51c410b@34.94.177.254:26656
        - 7a117e7906d8428ad20341aca94af03c980c11d8@34.102.55.164:26656

storage:
  enabled: true
  local: false
  entities:
    sequencerSharedStorage:
      size: 1Ti
      storageClassName: premium-rwo
      persistentVolumeName: "sequencer-shared-storage"
      path: "/data/sequencer-data"

serviceMonitor:
  enabled: true

ingress:
  p2p:
    enabled: false

resources:
  cometbft:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  sequencer:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 2000m
      memory: 4Gi
